### ISSUE TITLE
`esbuild` Build Error with `vite@^2.2.0`

### ISSUE THREAD

**Issue by Penguinlay** [smnhgn/vite-plugin-package-version#1]
`@0.0.4` works fine with `vite` up to `2.1.5`.
```
 > error: Invalid define value (must be valid JSON syntax or a single identifier): 5.0.0-alpha.0

error when starting dev server:
Error: Build failed with 1 error:
error: Invalid define value (must be valid JSON syntax or a single identifier): 5.0.0-alpha.0
    at failureErrorWithLog (/Users/shein/kk/gh/uni5-ideal/node_modules/esbuild/lib/main.js:1224:15)
    at buildResponseToResult (/Users/shein/kk/gh/uni5-ideal/node_modules/esbuild/lib/main.js:936:32)
    at /Users/shein/kk/gh/uni5-ideal/node_modules/esbuild/lib/main.js:1035:20
    at /Users/shein/kk/gh/uni5-ideal/node_modules/esbuild/lib/main.js:568:9
    at handleIncomingPacket (/Users/shein/kk/gh/uni5-ideal/node_modules/esbuild/lib/main.js:657:9)
    at Socket.readFromStdout (/Users/shein/kk/gh/uni5-ideal/node_modules/esbuild/lib/main.js:535:7)
    at Socket.emit (node:events:369:20)
    at addChunk (node:internal/streams/readable:313:12)
    at readableAddChunk (node:internal/streams/readable:288:9)
    at Socket.Readable.push (node:internal/streams/readable:227:10)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by smnhgn** [comment]
Thank you for reporting @Penguinlay 
I pushed a new version to npm (v0.0.5)
